[project]
name = "video-1-perplexity"
version = "0.1.0"
description = "AI Evaluation Demo: Perplexity calculation using Hugging Face models"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "evaluate",
    "transformers",
    "torch",
    "accelerate"
]
